### Sign up
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "migueljomartinez+4@gmail.com",
  "password": "unicornio-verde-con-coco"
}

### Sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "migueljomartinez+4@gmail.com",
  "password": "unicornio-verde-con-coco"
}

### Get user by ID
GET http://localhost:3000/auth/3

### Get user by email
GET http://localhost:3000/auth?email=migueljomartinez@gmail.com

### Update user by id
PUT http://localhost:3000/auth/5
content-type: application/json

{
  "password": "0070078"
}

### Remove user by id
DELETE http://localhost:3000/auth/4

### Set color
POST http://localhost:3000/auth/colors/lightcoral

### Get color
GET http://localhost:3000/auth/colors
